// #![cfg_attr(
//     all(not(debug_assertions), target_os = "windows"),
//     windows_subsystem = "windows"
// )]
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod commands;
mod services;

use commands::player_commands;
use souchy_tauri_specta::Builder;
use specta_typescript::Typescript;

fn main() {
    dotenv::dotenv().ok();

    let specta_builder = build_specta();

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            // Setup specta and generate bindings
            specta_builder.mount_events(app);
            generate_bindings(specta_builder);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

fn build_specta() -> souchy_tauri_specta::Builder {
    let specta_builder =
        Builder::<tauri::Wry>::new().commands(souchy_tauri_specta::collect_commands![
            player_commands::load_and_play_file,
            player_commands::pause,
            player_commands::resume,
            player_commands::stop,
        ]);

    specta_builder
}

fn generate_bindings(specta_builder: souchy_tauri_specta::Builder) {
    println!("Generating TypeScript bindings...");
    #[cfg(debug_assertions)]
    specta_builder
        .export_per_file(
            Typescript::default()
                .formatter(specta_typescript::formatter::prettier)
                .header("/* eslint-disable */")
                .framework_header("/* DO NOT EDIT. AUTO-GENERATED BY SPECTA */"),
            "../src/generated/specta",
        )
        .expect("Failed to export typescript bindings");
}
